name: Other
main: im.limbo.Main
authors: [Limbo]
version: 1.0
api-version: 1.18
depend: [Vault]

commands:
  spawn:
      description: set spawn point
  setspawn:
      description: spawn
  balance:
      description: balance of player
  lreload:
      description: reload config.

permissions:
  other.*:
    description: For all command
    default: op
    children:
      other.admin: true
  other.spawn:
    default: true
  other.setspawn:
    default: false
  other.admin:
    default: false
    children:
      other.spawn: true
      other.setspawn: true
      other.reload: true